platform: linux
image_resource:
  type: docker-image
  source:
    repository: mumoshu/dcind
inputs:
  - name: project-code
  - name: project-image-tar
run:
  path: project-code/ci/scripts/run-tests-rspec.sh
