default: &default
  adapter: postgresql
  database: <%= ENV["DB_NAME"] %>
  encoding: unicode
  password: <%= ENV["DB_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USERNAME"] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
