default: &default
  adapter: postgresql
  database: <%= ENV["DB_NAME"] %>
  encoding: unicode
  host: <%= ENV["DB_HOST"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USERNAME"] %>

development:
  <<: *default

test: &test
  <<: *default

production:
  <<: *default

cucumber:
  <<: *test
