resources:
  - name: project-code
    type: git
    source:
      uri: https://github.com/jamesgoodhouse/Rails5TestApp
      branch: master
  - name: project-bundle
    type: git
    source:
      uri: https://github.com/jamesgoodhouse/Rails5TestApp-bundle
      branch: master
  - name: ruby-2.3.1-image
    type: docker-image
    source:
      repository: jamgood96/ruby
      tag: "2.3.1"
  - name: project-image
    type: docker-image
    source:
      repository: jamgood96/rails5testapp
      username: jamgood96
      password: {{docker-hub-password}}
jobs:
  - name: build-and-test
    plan:
      - aggregate:
        - get: project-code
          trigger: true
        - get: project-bundle
          params: {save: true}
        - get: ruby-2.3.1-image
          params: {save: true}
      - task: bundle-gems
        file: project-code/ci/tasks/bundle-gems.yml
      - task: build-image
        privileged: true
        file: project-code/ci/tasks/build-image.yml
      - aggregate:
        - task: rspec
          privileged: true
          file: project-code/ci/tasks/run-tests-rspec.yml
        - task: cucumber
          privileged: true
          file: project-code/ci/tasks/run-tests-cucumber.yml
      - put: project-image
        params:
          import_file: project-image-tar/image.tar
  # - name: things-and-stuff
  #   plan:
  #     - get: project-image
  #       passed: [build-and-test]
