resource_types:
  - name: rsync-resource
    type: docker-image
    source:
      repository: mrsixw/concourse-rsync-resource
      tag: latest

resources:
  - name: project-code
    type: git
    source:
      uri: https://github.com/jamesgoodhouse/Rails5TestApp
      branch: master

  - name: ruby-2.3.1-image
    type: docker-image
    source:
      repository: jamgood96/ruby
      tag: "2.3.1"

  - name: project-image
    type: docker-image
    source:
      repository: jamgood96/rails5testapp
      username: jamgood96
      password: {{docker-hub-password}}

  - name: build-cache
    type: rsync-resource
    source:
      server: 192.168.100.4
      port: 22
      base_dir: /home/vagrant/caches
      user : vagrant
      private_key: {{private_key}}

jobs:
  - name: build-and-test
    plan:
      - aggregate:
        - get: project-code
          trigger: true

        # - get: project-image
        #   params: {save: true}

        - get: ruby-2.3.1-image
          params: {save: true}

        - get: build-cache

      - task: bundle-gems
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: jamgood96/ruby
              tag: "2.3.1-dev"
          inputs:
            - name: build-cache
            - name: project-code
          outputs:
            - name: bundle
          run:
            path: ./project-code/ci/ci.sh
            args: [bundle_gems]

      - task: compile-assets
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: jamgood96/ruby
              tag: "2.3.1-dev"
          inputs:
            - name: bundle
            - name: project-code
          outputs: [name: assets]
          run:
            path: pwd
            # path: ./project-code/ci/ci.sh
            # args: [compile_assets]

      - task: build-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: mumoshu/dcind
          inputs:
            - name: assets
            - name: build-cache
            - name: bundle
            - name: project-code
            - name: ruby-2.3.1-image
          outputs: [name: project-image-tar]
          run:
            path: ./project-code/ci/ci.sh
            args: [build_image]

      - task: cleanup
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: alpine
          inputs:
            - name: bundle
            - name: project-code
            - name: project-image-tar
          outputs:
            - name: build-cache
          run:
            path: ./project-code/ci/ci.sh
            args: [cleanup]
        ensure:
          put: build-cache
          params: {sync_dir: build-cache}
  #
  #     - aggregate:
  #       - task: rspec
  #         privileged: true
  #         config:
  #           platform: linux
  #           image_resource:
  #             type: docker-image
  #             source:
  #               repository: mumoshu/dcind
  #           inputs:
  #             - name: project-code
  #             - name: project-image-tar
  #           run:
  #             dir: project-code
  #             path: ./ci/ci.sh
  #             args: [rspec]
  #       - task: cucumber
  #         privileged: true
  #         config:
  #           platform: linux
  #           image_resource:
  #             type: docker-image
  #             source:
  #               repository: mumoshu/dcind
  #           inputs:
  #             - name: project-code
  #             - name: project-image-tar
  #           run:
  #             dir: project-code
  #             path: ./ci/ci.sh
  #             args: [cucumber]
  #
      - put: project-image
        params:
          load_file: project-image-tar/image.tar.bz2
          load_repository: jamgood96/rails5testapp
          load_tag: latest
  # # - name: things-and-stuff
  # #   plan:
  # #     - get: project-image
  # #       passed: [build-and-test]
