resource_types:
  - name: rsync-resource
    type: docker-image
    source:
      repository: mrsixw/concourse-rsync-resource
      tag: latest

resources:
  - name: git-repo
    type: git
    source:
      uri: https://github.com/jamesgoodhouse/Rails5TestApp
      branch: master

  - name: build-cache
    type: rsync-resource
    source:
      server: 192.168.100.4
      port: 22
      base_dir: /home/vagrant/caches/build-cache
      user : vagrant
      private_key: {{private_key}}

  - name: image-cache
    type: rsync-resource
    source:
      server: 192.168.100.4
      port: 22
      base_dir: /home/vagrant/caches/image-cache
      user : vagrant
      private_key: {{private_key}}

  - name: image-registry
    type: docker-image
    source:
      repository: jamgood96/rails5testapp
      username: jamgood96
      password: {{docker-hub-password}}

jobs:
  - name: build-image
    plan:
      - aggregate:
        - get: git-repo
          trigger: true
        - get: build-cache

      - task: bundle-gems
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: jamgood96/ruby
              tag: "2.3.1-dev"
          inputs:
            - name: build-cache
            - name: git-repo
          outputs:
            - name: bundle
            - name: bundle-tar
          run:
            path: ./git-repo/ci/ci.sh
            args: [bundle_gems]

      - task: compile-assets
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: jamgood96/ruby
              tag: "2.3.1-dev"
          inputs:
            - name: bundle
            - name: git-repo
          outputs:
            - name: assets
          run:
            path: ./git-repo/ci/ci.sh
            args: [compile_assets]

      - get: image-cache

      - task: build-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: mumoshu/dcind
          inputs:
            - name: assets
            - name: build-cache
            - name: image-cache
            - name: bundle
            - name: git-repo
          outputs:
            - name: image-tar
          run:
            path: ./git-repo/ci/ci.sh
            args: [build_image]

      - aggregate:
        - put: build-cache
          params:
            sync_dir: bundle-tar
        - put: image-cache
          params:
            sync_dir: image-tar

  - name: tests
    plan:
      - get: image-cache
        trigger: true
        passed: [build-image]
      - get: git-repo
        passed: [build-image]

      - aggregate:
        - task: rspec
          privileged: true
          config:
            platform: linux
            image_resource:
              type: docker-image
              source:
                repository: mumoshu/dcind
            inputs:
              - name: git-repo
              - name: image-cache
            run:
              path: ./git-repo/ci/ci.sh
              args: [rspec]

        - task: cucumber
          privileged: true
          config:
            platform: linux
            image_resource:
              type: docker-image
              source:
                repository: mumoshu/dcind
            inputs:
              - name: git-repo
              - name: image-cache
            run:
              path: ./git-repo/ci/ci.sh
              args: [cucumber]

      # - put: image-registry
      #   params:
      #     load_file: image-cache/image.tar.bz2
      #     load_repository: jamgood96/rails5testapp
      #     load_tag: latest
