resources:
  - name: code-repo
    type: git
    source:
      uri: https://github.com/jamesgoodhouse/Rails5TestApp
      branch: master
jobs:
  - name: build image
    plan:
      - get: code-repo
        trigger: true
      - task: build image
        file: code-repo/ci/tasks/build-image.yml
        privileged: true
